### ISSUE TITLE
Change timetable cells span

### ISSUE THREAD

**Issue by MachHach** [Raphx/vmlauncher-client#1]
Timetable should show book-able slots for each of the 24 hours in a day, spanning across the whole timetable. See this server [issue](https://github.com/Raphx/vmlauncher-backend/issues/4).

The current implementation is unable to show time slots created from a user of a different time zone as the start-of-day and end-of-day slots are truncated.

**Comment by Raphx** [comment]
We could paginate it if 24 slots does not fit well to the application width.

For instance, this is what it looks like on the column header displaying time slots:

    | < | 09 | 10 | 11 | 12 | 13 | > |

Click on the `<`, the result will be:

    | < | 08 | 09 | 10 | 11 | 12 | > |

This is a nice-to-have. 😉

**Comment by MachHach** [comment]
Agreed on the pagination part.
Even with only 7 slots (during development), it is becoming a hassle (and ugly).

**Comment by MachHach** [comment]
Note that this is being worked as part of `feature/Timetable` branch.

**Comment by Raphx** [comment]
Project maintenance ended.
